### PR TITLE
Updated more filter modal; closes  #54

### LINKED ISSUE #54: MoreFilters modal fix
Need to fix what I have currently for **MoreFilters coomponent** to work as a modal of sorts when clicking the _`morefilters button`_ on **results pages**.

Currently it opens properly but the close button was not working. I should have it fixed sometime today.

### PR DESCRIPTION
**Pull request by Trevis42**
Added better/fixed modal functionality of the `MoreFilters` component.

### CODE REVIEW

**Review by mrterranova — APPROVED** [review]
I'm not sure about some of the package stuff or app stuff, but if it isn't interferring then all is well

**Comment by Trevis42** [comment]
> 
> I'm not sure about some of the package stuff or app stuff, but if it isn't interferring then all is well

Package stuff should be fine. when I went to `npm install`, the npm audit said there was 1 with high audit issue or whatever it says... so I had it fix it. always good to upgrade if we can but sometimes upgrading can break things. when that happens I generally don't push those changes.

App stuff was to add my modal to the app modules and whatnot and get it up and working. That wont effect anything.

**Comment by Trevis42** [comment]
Fixed merge conflicts. looks like it was just an issue mostly with my component. I misplaced a div when move stuff around. just cut and pasted my component in the same spot on current setup instead of using the one I pushed.

**Review by BrianLoveGa — APPROVED** [review]
i'll allow it!

**Pull request merged**
